/**
 * No machine-identifying value reaches the public repo (Node).
 *
 * **aegis-trust is a PUBLIC repository.** Everything committed here is
 * published the moment a branch is pushed, and stays published — a later
 * deletion does not un-cache or un-index it.
 *
 * WHY THIS EXISTS. The attestation conformance corpus is generated by running
 * the real Core binary and keeping what it produced. What it produces includes
 * `host_fingerprint`, which is `"host_" + sha256(hostname)[:8]` — a 64-bit
 * commitment to the generating machine's hostname, brute-forceable against a
 * wordlist. The first generated corpus carried it 208 times, plus the absolute
 * scratchpad path (with a session UUID) the binary had walked. Both sit inside
 * the signed message, so neither can be edited out afterwards: the corpus has
 * to be regenerated from a clean root by a binary that emits a neutral
 * fingerprint (Core added AEGIS_ATTEST_HOST_FINGERPRINT_FOR_TEST for this).
 *
 * Nothing caught it. `.gitleaks.toml` here is allowlist-only — it declares zero
 * rules, so it matches nothing. It was found by hand, once, because the
 * visibility of the repository happened to be checked before a push. That is
 * not a control.
 *
 * NO UNMEASURED EXCLUSIONS. This guard has been wrong three times in the same
 * way, and each time the fault was a place it had quietly agreed not to look:
 *
 *   1. its scan covered conformance/ and docs/ only — and its own source,
 *      outside that scope, held the last four literal copies of the real
 *      fingerprint, in the strings asserting that an undeclared fingerprint is
 *      reported;
 *   2. it filtered those directories to .json and .md, which hid a real
 *      home-directory path in a committed .log;
 *   3. it skipped binary suffixes and silently swallowed undecodable files,
 *      neither of which anyone had counted — and when finally measured, both
 *      sets were empty, so the exclusions had been buying nothing at all.
 *
 * So it now reads EVERY tracked file as bytes — no suffix filter, no decode
 * fallback, no directory scope — and counts what it could not read, requiring
 * that number to be zero. Every remaining exclusion is declared by value or by
 * path, carries a reason, and is itself tested for still being necessary.
 *
 * Mirror: python/tests/test_published_artifact_hygiene.py.
 */

import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

const REPO = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

// Proof samples are ASSEMBLED from fragments rather than written out, for two
// reasons: this repo's boundary gate refuses concrete home-directory paths in
// source (a guard that cannot be committed is not a guard), and the scan below
// reads this very file, so a well-formed literal here would be a finding.
const USER_DIR = "/" + "Users" + "/";
const SESSION_DIR = "/" + "claude" + "-501/";

interface Rule {
  source: string;
  why: string;
  sample: string;
}

/** Patterns that must not appear in any tracked file. */
const RULES: Record<string, Rule> = {
  "aegis-host-fingerprint": {
    source: "host_[0-9a-f]{16}\\b",
    why:
      "an Aegis host fingerprint is sha256(hostname) truncated to 8 bytes — a "
      + "64-bit commitment to a real machine's hostname, brute-forceable against "
      + "a wordlist. Regenerate with AEGIS_ATTEST_HOST_FINGERPRINT_FOR_TEST set.",
    sample: "host_" + "0".repeat(16),
  },
  "home-directory-path": {
    source: "/(?:Users|home)/[A-Za-z0-9._-]+/",
    why: "an absolute path under a home directory names the machine's owner and layout.",
    sample: USER_DIR + "example" + "/projects/x",
  },
  "session-scratchpad-path": {
    source:
      "/claude-[0-9]+/|/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/",
    why:
      "a session scratchpad path embeds a session UUID and the machine's "
      + "directory layout. Generate fixtures under a short, generic root.",
    sample: "/private/tmp" + SESSION_DIR + "foo",
  },
};

/**
 * Fingerprint values that are declared synthetic fixtures rather than derived
 * from any machine. Exempted BY VALUE, not by file: a file-level exemption
 * would switch a whole file off, while this keeps every other fingerprint red.
 */
const DECLARED_SYNTHETIC: Record<string, string> = {
  host_0000000000000000:
    "the value Core emits under AEGIS_ATTEST_HOST_FINGERPRINT_FOR_TEST. Core "
    + "added that override after this guard found its real fingerprint in the "
    + "generated vectors; it affects the attest output only and never the "
    + "sealing key, which stays derived from the real fingerprint.",
  host_0000000000000001:
    "the corpus fixture host. Constructed, not derived: the synthetic cases are "
    + "signed in-repo, so they never need a real machine's fingerprint.",
  host_ffffffffffffffff:
    "the 'attestation about another machine' fixture. Constructed, and "
    + "deliberately unlike the fixture host so the host check has something to "
    + "disagree with.",
};

/** "<relative path>::<rule>" -> why it is acceptable. Every entry must argue
 * for itself; an undocumented exemption list is where a guard quietly stops
 * meaning anything. */
const ALLOWED: Record<string, string> = {};

/** Every file git tracks. No suffix filter: the .log that carried a real home
 * path was invisible while this was limited to .json and .md. */
function trackedFiles(): string[] {
  const out = execFileSync("git", ["ls-files", "-z"], {
    cwd: REPO,
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
  });
  return out
    .split("\0")
    .filter((n) => n !== "")
    .map((n) => join(REPO, n))
    .sort();
}

function rel(file: string): string {
  return relative(REPO, file).split(sep).join("/");
}

/**
 * Undeclared hits in one file, read as BYTES.
 *
 * latin1 maps each byte to the code point of the same value, so an ASCII regex
 * over it is a byte search — nothing is skipped for being binary or
 * undecodable.
 */
function scan(file: string): string[] {
  const key = rel(file);
  const text = readFileSync(file).toString("latin1");
  const problems: string[] = [];
  for (const [name, rule] of Object.entries(RULES)) {
    if (`${key}::${name}` in ALLOWED) continue;
    let found = text.match(new RegExp(rule.source, "g")) ?? [];
    if (name === "aegis-host-fingerprint") {
      found = found.filter((f) => !(f in DECLARED_SYNTHETIC));
    }
    if (found.length > 0) {
      problems.push(
        `${key}: ${found.length} undeclared ${name} (first: ${found[0]}) — ${rule.why}`,
      );
    }
  }
  return problems;
}

/**
 * Does this fingerprint look chosen rather than hashed?
 *
 * A real fingerprint is sha256 output, so its 16 hex digits are spread across
 * the alphabet. A value built by hand uses one or two symbols. Three is the
 * cut: it admits every plausible fixture and rejects any hash.
 */
function isVisiblyConstructed(value: string): boolean {
  return new Set(value.replace("host_", "")).size <= 3;
}

const FINGERPRINT = RULES["aegis-host-fingerprint"];

describe("published artifact hygiene", () => {
  it("the scan is not vacuous", () => {
    // A guard that silently matched nothing reports a clean result, which is
    // the exact failure mode it exists to remove.
    expect(trackedFiles().length).toBeGreaterThanOrEqual(100);
    expect(Object.keys(RULES).length).toBeGreaterThan(0);
  });

  it("nothing is silently skipped", () => {
    // The third way this guard was wrong: it swallowed unreadable files. A file
    // it cannot read is not a file without findings.
    const unreadable: string[] = [];
    for (const file of trackedFiles()) {
      try {
        readFileSync(file);
      } catch (err) {
        unreadable.push(`${rel(file)}: ${(err as Error).name}`);
      }
    }
    expect(unreadable, `not scanned: ${unreadable.join(", ")}`).toEqual([]);
  });

  it("the patterns match what they claim", () => {
    for (const [name, rule] of Object.entries(RULES)) {
      expect(new RegExp(rule.source).test(rule.sample), name).toBe(true);
    }
  });

  it("the patterns do not match innocent text", () => {
    // A pattern that matched everything would make the tree permanently
    // un-publishable and the guard would be removed.
    const innocent =
      "/var/lib/aegis/capsules/bodies/b1.bin host_fingerprint /tmp/vectors";
    for (const [name, rule] of Object.entries(RULES)) {
      expect(new RegExp(rule.source).test(innocent), name).toBe(false);
    }
  });

  it("visibly-constructed rejects a real fingerprint", () => {
    // The failing direction, observed rather than assumed. The sample is
    // hash-SHAPED and was never any machine's: the rule under test is "does
    // this look hashed", so a genuine value was never needed.
    const hashShaped = "host_" + "9a3f21b7" + "d4e6c085";
    expect(new RegExp("^" + FINGERPRINT.source + "$").test(hashShaped)).toBe(true);
    expect(isVisiblyConstructed(hashShaped)).toBe(false);
    for (const value of Object.keys(DECLARED_SYNTHETIC)) {
      expect(isVisiblyConstructed(value), value).toBe(true);
    }
  });

  it("the declared filter does not hide an undeclared fingerprint", () => {
    const undeclared = "host_" + "9a3f21b7" + "d4e6c085";
    const text = `host_0000000000000001 and ${undeclared}`;
    const found = (text.match(new RegExp(FINGERPRINT.source, "g")) ?? []).filter(
      (f) => !(f in DECLARED_SYNTHETIC),
    );
    expect(found).toEqual([undeclared]);
  });

  it("declared synthetic values are justified", () => {
    expect(Object.keys(DECLARED_SYNTHETIC).length).toBeGreaterThan(0);
    for (const [value, reason] of Object.entries(DECLARED_SYNTHETIC)) {
      expect(new RegExp("^" + FINGERPRINT.source + "$").test(value), value).toBe(true);
      expect(reason.length, `${value}: reason too thin`).toBeGreaterThan(40);
      expect(isVisiblyConstructed(value), value).toBe(true);
    }
  });

  it("file exemptions are justified and still needed", () => {
    // An exemption nobody measures is a place the guard has agreed not to look.
    // So each must name a real file and a real pattern, give a reason, and —
    // the part that keeps the list from rotting — still be necessary.
    for (const [key, reason] of Object.entries(ALLOWED)) {
      const [path, name] = key.split("::");
      expect(RULES[name], `${path}: exemption for unknown pattern ${name}`).toBeDefined();
      expect(reason.length, `${key}: reason too thin`).toBeGreaterThan(60);
      const text = readFileSync(join(REPO, path)).toString("latin1");
      expect(
        new RegExp(RULES[name].source).test(text),
        `${key}: the exemption is no longer needed — remove it rather than carrying it`,
      ).toBe(true);
    }
  });

  it("no machine-identifying value in any tracked file", () => {
    // One test over every tracked file, not one per file: the failure has to
    // list every offending file at once, or a fix for the first hides the rest
    // until the next run.
    const problems = trackedFiles().flatMap(scan);
    expect(
      problems,
      problems.join("\n")
        + "\n\naegis-trust is PUBLIC. Pushing this publishes the value, and a "
        + "later deletion does not un-index it.",
    ).toEqual([]);
  });

  it("declared synthetic values are still in use", () => {
    // An exemption nobody measures is a place the guard has agreed not to look,
    // and one nobody uses is a place it has agreed not to look at nothing. This
    // file is excluded from the count on purpose: a list that justified itself
    // by mentioning its own entries would always pass.
    const here = fileURLToPath(import.meta.url);
    const corpus = trackedFiles()
      .filter((f) => f !== here)
      .map((f) => readFileSync(f).toString("latin1"));
    const unused = Object.keys(DECLARED_SYNTHETIC).filter(
      (value) => !corpus.some((text) => text.includes(value)),
    );
    expect(
      unused,
      `declared synthetic values that nothing uses: ${unused}. Remove them — an `
        + "exemption kept for a value that is gone is a hole held open for nothing.",
    ).toEqual([]);
  });
});
