"""No machine-identifying value reaches the public repo (Python).

**aegis-trust is a PUBLIC repository.** Everything committed here is published
the moment a branch is pushed, and stays published — a later deletion does not
un-cache or un-index it.

WHY THIS EXISTS. The attestation conformance corpus is generated by running the
real Core binary and keeping what it produced. What it produces includes
``host_fingerprint``, which is ``"host_" + sha256(hostname)[:8]`` — a 64-bit
commitment to the generating machine's hostname, brute-forceable against a
wordlist. The first generated corpus carried it 208 times, plus the absolute
scratchpad path (with a session UUID) the binary had walked. Both sit inside the
signed message, so neither can be edited out afterwards: the corpus has to be
regenerated from a clean root by a binary that emits a neutral fingerprint
(Core added ``AEGIS_ATTEST_HOST_FINGERPRINT_FOR_TEST`` for exactly this).

Nothing caught it. ``.gitleaks.toml`` here is allowlist-only — it declares zero
rules, so it matches nothing. It was found by hand, once, because the
visibility of the repository happened to be checked before a push. That is not
a control.

NO UNMEASURED EXCLUSIONS. This guard has been wrong three times in the same
way, and each time the fault was a place it had quietly agreed not to look:

1. its scan covered ``conformance/`` and ``docs/`` only — and its own source,
   outside that scope, held the last four literal copies of the real
   fingerprint, in the strings asserting that an undeclared fingerprint is
   reported;
2. it filtered those directories to ``.json`` and ``.md``, which hid a real
   home-directory path in a committed ``.log``;
3. it skipped binary suffixes and silently swallowed undecodable files, neither
   of which anyone had counted — and when finally measured, both sets were
   empty, so the exclusions had been buying nothing at all.

So it now reads **every tracked file as bytes** — no suffix filter, no decode
fallback, no directory scope — and counts what it could not read, requiring that
number to be zero. Every remaining exclusion is declared by value or by path,
carries a reason, and is itself tested for still being necessary.

Mirror: node/tests/publishedArtifactHygiene.test.ts.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

# Proof samples are ASSEMBLED from fragments rather than written out, for two
# reasons: this repo's boundary gate refuses concrete home-directory paths in
# source (a guard that cannot be committed is not a guard), and the scan below
# reads this very file, so a well-formed literal here would be a finding.
_USER_DIR = "/" + "Users" + "/"
_SESSION_DIR = "/" + "claude" + "-501/"

#: Patterns that must not appear in any tracked file.
PATTERNS: dict[str, tuple[re.Pattern[bytes], str]] = {
    "aegis-host-fingerprint": (
        re.compile(rb"host_[0-9a-f]{16}\b"),
        "an Aegis host fingerprint is sha256(hostname) truncated to 8 bytes — a "
        "64-bit commitment to a real machine's hostname, brute-forceable "
        "against a wordlist. Regenerate with "
        "AEGIS_ATTEST_HOST_FINGERPRINT_FOR_TEST set.",
    ),
    "home-directory-path": (
        re.compile(rb"/(?:Users|home)/[A-Za-z0-9._-]+/"),
        "an absolute path under a home directory names the machine's owner and layout.",
    ),
    "session-scratchpad-path": (
        re.compile(
            rb"/claude-[0-9]+/"
            rb"|/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/"
        ),
        "a session scratchpad path embeds a session UUID and the machine's "
        "directory layout. Generate fixtures under a short, generic root.",
    ),
}

#: Fingerprint values that are declared synthetic fixtures rather than derived
#: from any machine. Exempted BY VALUE, not by file: a file-level exemption
#: would switch a whole file off, while this keeps every other fingerprint red.
DECLARED_SYNTHETIC = {
    "host_0000000000000000": (
        "the value Core emits under AEGIS_ATTEST_HOST_FINGERPRINT_FOR_TEST. Core "
        "added that override after this guard found its real fingerprint in the "
        "generated vectors; it affects the attest output only and never the "
        "sealing key, which stays derived from the real fingerprint."
    ),
    "host_0000000000000001": (
        "the corpus fixture host. Constructed, not derived: the synthetic cases "
        "are signed in-repo, so they never need a real machine's fingerprint."
    ),
    "host_ffffffffffffffff": (
        "the 'attestation about another machine' fixture. Constructed, and "
        "deliberately unlike the fixture host so the host check has something "
        "to disagree with."
    ),
}

#: (relative path, pattern name) -> why it is acceptable. Every entry must argue
#: for itself; an undocumented exemption list is where a guard quietly stops
#: meaning anything (same discipline as `not_corpora_reasons`).
ALLOWED: dict[tuple[str, str], str] = {}


def _tracked_files() -> list[Path]:
    """Every file git tracks. No suffix filter: the .log that carried a real
    home path was invisible while this was limited to .json and .md."""
    out = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=True,
    )
    return sorted(REPO / n for n in out.stdout.split("\0") if n)


def _scan(path: Path) -> list[tuple[str, list[str]]]:
    """Undeclared hits in one file, read as BYTES.

    Bytes rather than text so nothing is skipped for being binary or
    undecodable: the values hunted here are ASCII, so they are findable in any
    file that contains them.
    """
    rel = str(path.relative_to(REPO))
    data = path.read_bytes()
    out: list[tuple[str, list[str]]] = []
    for name, (pattern, _) in PATTERNS.items():
        if (rel, name) in ALLOWED:
            continue
        found = [m.decode("ascii", "replace") for m in pattern.findall(data)]
        if name == "aegis-host-fingerprint":
            found = [f for f in found if f not in DECLARED_SYNTHETIC]
        if found:
            out.append((name, found))
    return out


def _is_visibly_constructed(value: str) -> bool:
    """Does this fingerprint look chosen rather than hashed?

    A real fingerprint is sha256 output, so its 16 hex digits are spread across
    the alphabet. A value built by hand uses one or two symbols. Three is the
    cut: it admits every plausible fixture and rejects any hash — the chance of
    a real fingerprint using three or fewer distinct digits is about one in a
    billion, and it would still have to be added to the list deliberately.
    """
    return len(set(value.removeprefix("host_"))) <= 3


# ---------------------------------------------------------------------------
# The guard proves itself before it judges anything.
# ---------------------------------------------------------------------------


def test_the_scan_is_not_vacuous() -> None:
    """A guard that silently matched nothing reports a clean result, which is
    the exact failure mode it exists to remove."""
    assert len(_tracked_files()) >= 100
    assert PATTERNS


def test_nothing_is_silently_skipped() -> None:
    """The third way this guard was wrong: it swallowed unreadable files.

    A file it cannot read is not a file without findings, so the count is
    asserted rather than shrugged off.
    """
    unreadable = []
    for path in _tracked_files():
        try:
            path.read_bytes()
        except OSError as exc:
            unreadable.append(f"{path.relative_to(REPO)}: {exc.__class__.__name__}")
    assert not unreadable, (
        "these tracked files could not be read, so they were not scanned: "
        + ", ".join(unreadable)
    )


def test_the_patterns_match_what_they_claim() -> None:
    """Each pattern is proved against a sample it must catch, so a typo cannot
    leave it matching nothing forever."""
    samples = {
        "aegis-host-fingerprint": "host_" + "0" * 16,
        "home-directory-path": _USER_DIR + "example" + "/projects/x",
        "session-scratchpad-path": "/private/tmp" + _SESSION_DIR + "foo",
    }
    assert set(samples) == set(PATTERNS), "a pattern has no proof sample"
    for name, sample in samples.items():
        assert PATTERNS[name][0].search(sample.encode()), f"{name} misses its sample"


def test_the_patterns_do_not_match_innocent_text() -> None:
    """The other half of the pair: a pattern that matched everything would make
    the tree permanently un-publishable and the guard would be removed."""
    innocent = b"/var/lib/aegis/capsules/bodies/b1.bin host_fingerprint /tmp/vectors"
    for name, (pattern, _) in PATTERNS.items():
        assert not pattern.search(innocent), f"{name} matches innocent text"


def test_visibly_constructed_rejects_a_real_fingerprint() -> None:
    """The failing direction, observed rather than assumed.

    Without this, the rule only ever ran against values that already satisfied
    it — a check whose red has never been seen. The sample is hash-SHAPED and
    was never any machine's; the rule under test is "does this look hashed", so
    a genuine value was never needed.
    """
    hash_shaped = "host_" + "9a3f21b7" + "d4e6c085"
    assert PATTERNS["aegis-host-fingerprint"][0].fullmatch(hash_shaped.encode())
    assert not _is_visibly_constructed(hash_shaped)
    for value in DECLARED_SYNTHETIC:
        assert _is_visibly_constructed(value), value


def test_the_declared_filter_does_not_hide_an_undeclared_fingerprint() -> None:
    """Positive control for the value exemption itself."""
    undeclared = "host_" + "9a3f21b7" + "d4e6c085"
    text = f"host_0000000000000001 and {undeclared}".encode()
    found = [
        m.decode()
        for m in PATTERNS["aegis-host-fingerprint"][0].findall(text)
        if m.decode() not in DECLARED_SYNTHETIC
    ]
    assert found == [undeclared]


def test_declared_synthetic_values_are_justified() -> None:
    assert DECLARED_SYNTHETIC, "no declared fixtures; the filter is inert"
    for value, reason in DECLARED_SYNTHETIC.items():
        assert PATTERNS["aegis-host-fingerprint"][0].fullmatch(value.encode()), value
        assert len(reason) > 40, f"{value}: reason too thin to audit"
        assert _is_visibly_constructed(value), f"{value}: not visibly constructed"


def test_file_exemptions_are_justified_and_still_needed() -> None:
    """An exemption nobody measures is a place the guard has agreed not to look.

    So each one must name a real file, a real pattern, give a reason, and — the
    part that keeps the list from rotting — still be necessary: an exemption
    whose file no longer trips the rule is removed, not carried.
    """
    for (rel, name), reason in ALLOWED.items():
        assert name in PATTERNS, f"{rel}: exemption for unknown pattern {name}"
        assert len(reason) > 60, f"{rel}/{name}: reason too thin to audit"
        path = REPO / rel
        assert path.is_file(), f"{rel}: stale exemption, the file is gone"
        pattern = PATTERNS[name][0]
        assert pattern.search(path.read_bytes()), (
            f"{rel}/{name}: the exemption is no longer needed — the file does "
            "not trip this rule. Remove it rather than carrying it."
        )


# ---------------------------------------------------------------------------
# The scan itself.
# ---------------------------------------------------------------------------


def test_no_machine_identifying_value_in_any_tracked_file() -> None:
    """One test over every tracked file, not one test per file: the failure has
    to list every offending file at once, or a fix for the first one hides the
    rest until the next run."""
    problems = [
        f"{path.relative_to(REPO)}: {len(found)} undeclared {name} "
        f"(first: {found[0]!r}) — {PATTERNS[name][1]}"
        for path in _tracked_files()
        for name, found in _scan(path)
    ]
    assert not problems, (
        "\n".join(problems)
        + "\n\naegis-trust is PUBLIC. Pushing this publishes the value, and a "
        "later deletion does not un-index it."
    )


def test_declared_synthetic_values_are_still_in_use() -> None:
    """An exemption nobody measures is a place the guard has agreed not to look,
    and one nobody uses is a place it has agreed not to look at nothing.

    Each declared value must actually appear somewhere else in the tree. This
    file is excluded from the count on purpose: a list that justified itself by
    mentioning its own entries would always pass. Mirrors the same rule the Core
    session put on its synthetic list.
    """
    here = Path(__file__).resolve()
    corpus: list[bytes] = []
    for path in _tracked_files():
        if path.resolve() == here:
            continue
        corpus.append(path.read_bytes())
    unused = [
        value
        for value in DECLARED_SYNTHETIC
        if not any(value.encode() in data for data in corpus)
    ]
    assert not unused, (
        f"declared synthetic values that nothing uses: {unused}. Remove them — "
        "an exemption kept for a value that is gone is a hole held open for "
        "nothing."
    )
